### ISSUE TITLE
TODO: integrate new Java and Go sdks

### ISSUE THREAD

**Issue by paulyuk** [dapr/quickstarts#1078]
Part 2 of Updating all Dapr.* SDKs to release-1.14 equivalent versions

This completes the task with Go and Java SDKs.  The other languages are done and merged by PR #1073 

## Checklist

* [ ] golang `require github.com/dapr/go-sdk v1.10.0`
Go RC coming @JoshVanL, @mikeee, @yaron2  ?
* [ ] java `<version>1.12.0</version>`
Go RC coming @artursouza ?
* [x] Checks/tests pass

**Comment by paulyuk** [comment]
Closed by #1082 #1085
