### ISSUE TITLE
Re-organize samples into quickstarts and samples

### ISSUE THREAD

**Issue by orizohar** [dapr/quickstarts#280]
This Epic describes the re-organizing of samples into two repositories. As the project is growing there is an growing set of samples that are contributed to Dapr. As some of the samples are used as a getting started learning path for new users, it is becoming harder to to maintain all samples in the same way and also hard for new users to orient themselves in the various samples.

## Goals

- Create a well defined small set of sample code examples that help new users get started quickly with Dapr. These are regularly maintained and verified on each release. This set should be small set as to keep the burden of verification on every release low.
- Provide a place for samples that do not fall into the above, these samples usually show specific or non basic use cases of Dapr through code and can range from very small specific examples to advanced or complex full fledged applications. These samples are verified as best effort for each release and will clearly state what release they were most recently tested on.
- SDK specific samples will remain in the SDK repos (no change)

## Tasks
- [x] Rename samples repo to - "quickstarts" (rename to keep the tag version history)
- [x] Update links that are now broken in the repo
- [x] Update links that are now broken in the docs
- [x]  Rename event-demos to "samples"
- [x]  Keep in quickstarts
                1. Hello world (state + service invocation)
		2. Pub sub
		3. Secret store
		4. Middleware
		5. Hello Kubernetes
		5 Binding
		7. Observability
                8. Distributed calculator
- [x]  Move to samples
		1. Functions and Keda
		2. Docker compose
		3. Minimal init
- [ ]  Refactor "next steps" section in the quickstarts to clearly point to a next recommended sample
- [x]  Add clear note in the Samples main README about "best effort" maintenance, remove versioning table. - we won't have versioning table in the renamed event-demos(samples) repo
